### PR TITLE
Add Romanian rules to slugify

### PR DESCRIPTION
**Pull request by gabiudrescu**

### CODE REVIEW

**Comment by florianeckerstorfer** [comment]
Could you please fix the tests and resolve the merge conflict?

**Comment by gabiudrescu** [comment]
I fixed the conflict, but regarding tests, I was expecting slugify to keep the casing when converting characters.

for example: ș becomes s while Ș becomes S.

from what I can see in the test, it's not. is this the correct behavior?

**Comment by florianeckerstorfer** [comment]
@gabiudrescu Slugify is a tool for URLs and URLs are case-insensitive, thus everything is converted to lower case.

**Comment by gabiudrescu** [comment]
fair enough. I have changed the tests. hope it's fine now.

**Pull request merged**
