### PR TITLE
Added hungarian rules

### PR DESCRIPTION
**Pull request by sajtosistvan**

### CODE REVIEW

**Comment by florianeckerstorfer** [comment]
Could you please add some tests for Hungarian?

**Comment by drtzack** [comment]
Could you please merge it? I really need it.

**Comment by florianeckerstorfer** [comment]
We need tests for Hungarian before I can merge this. In the best case the tests are provided by someone who speaks Hungarian. cc @sajtosistvan

**Comment by luczsoma** [comment]
@florianeckerstorfer Could you merge it into master? The rules are correct, one test for the Hungarian rules does exist indeed.

**Comment by franmomu** [comment]
I guess this can be closed because of https://github.com/cocur/slugify/pull/174

**Comment by florianeckerstorfer** [comment]
@franmomu Yeah, I think so too. Thanks.

**Pull request closed without merging**
