### PR TITLE
Add Georgian language support

### PR DESCRIPTION
**Pull request by TheGIBSON**
It's really necessary for the Georgian developers

### CODE REVIEW

**Comment by florianeckerstorfer** [comment]
Thanks for the contribution. It would be great if you could extend the tests with these new transliterations. Just add it to the `provider()` method in the [`SlugifyTest`](https://github.com/cocur/slugify/blob/master/tests/SlugifyTest.php#L184). With tests we can ensure that nobody in the future accidentally removes or changes these transliterations.

**Comment by TheGIBSON** [comment]
Done.

**Comment by florianeckerstorfer** [comment]
Thank you very much.

**Comment by TheGIBSON** [comment]
I'm glad to contribute

**Pull request merged**
