### PR TITLE
Add Yii2 component bridge

### PR DESCRIPTION
**Pull request by achretien**

### CODE REVIEW

**Comment by florianeckerstorfer** [comment]
There seems to be a problem with the dependencies. Can you look into this? If you have any question feel free to ping me.

**Comment by achretien** [comment]
Hi, I am not familiar with all the testing env you put in place.

As you can see in the [yii2 documentation](http://www.yiiframework.com/doc-2.0/guide-start-installation.html#installing-via-composer), the composer installation require the global package "fxp/composer-asset-plugin:~1.1.1".

I did find solution to install it on scrutinizer and appveyor

**Comment by florianeckerstorfer** [comment]
As far as I understand the docs of the composer-asset-plugin that it downloads Bower/NPM packages. Can we skip this? The dependency is only required for testing the bridge classes, so I guess there is no need to download frontend assets.

**Comment by achretien** [comment]
Yes you're right I will check if we can skip the requirement during composer installation

**Comment by achretien** [comment]
After reading the documentation and forums, one of the leading devs of the framework told in [this post](http://www.yiiframework.com/forum/index.php/topic/68361-do-i-need-to-install-fxpcomposer-asset-plugin-if-im-not-doing-front-end-development/page__view__findpost__p__290902) that dependency will be fixed it the next major release (so it could took some time).

**Pull request closed without merging**
