### PR TITLE
fix: php 8.4 deprecation about implicit null arguments

### PR DESCRIPTION
**Pull request by shyim**

### CODE REVIEW

**Comment by mitelg** [comment]
what about adding PHP 8.4 to the pipeline and to the composer.json?

**Review by florianeckerstorfer — APPROVED** [review]

**Comment by florianeckerstorfer** [comment]
Thank you very much 👏

**Comment by Evgeny1973** [comment]
@florianeckerstorfer Hello! When can we expect a new release?

**Comment by florianeckerstorfer** [comment]
@Evgeny1973 Yes, I will release a new version soon (hopefully this wek)

**Pull request merged**
