### PR TITLE
Fix: Use short array syntax

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] uses short array syntax

### CODE REVIEW

**Comment by OskarStark** [comment]
Why this change? this is totally useless and from now on you could not use this with older php versions

**Comment by localheinz** [comment]
@OskarStark 

See https://github.com/cocur/slugify/blob/master/composer.json#L19.

**Comment by OskarStark** [comment]
ok, is this needed to use 5.5.9, i know this is not part of the PR and then this PR is valid ofc, just asking

maybe @florianeckerstorfer can explain it to me?

**Comment by localheinz** [comment]
@OskarStark 

Of course it is not needed, but since the platform requirements indicate it is safe to use features present in PHP 5.5.9 and above, it should also be safe to use features present in PHP 5.4. 

Wondering, you are not installing using composer, or ignoring platform requirements?

**Pull request merged**
