### PR TITLE
[SYMFONY] Add ability to configure slugify

### PR DESCRIPTION
**Pull request by estahn**
* Moved the `CocurSlugifyExtension` into the `DependencyInjection` folder to comply with Symfony's bundle standard
* Added configuration for the slugify service (e.g. enable lowercase)

### CODE REVIEW

**Comment by florianeckerstorfer** [comment]
I don't think that is necessary. The Slugify bundle only contains three files, how I don't think we need to move them to separate namespaces.

**Comment by estahn** [comment]
@florianeckerstorfer Alright, i will move them all into one.

**Comment by estahn** [comment]
@florianeckerstorfer Actually it would be better to follow the symfony convention. The loader doesn't pick the config atm and the extension has been initialised in a wrong way.

https://symfony.com/doc/current/cookbook/bundles/extension.html#manually-registering-an-extension-class

**Comment by estahn** [comment]
@florianeckerstorfer Seems all good now. Do you need me to squash commits or is all good?

**Comment by florianeckerstorfer** [comment]
Since these are a lot of commits, yes, please squash.

**Comment by estahn** [comment]
@florianeckerstorfer done.

**Comment by florianeckerstorfer** [comment]
Thanks a lot.

**Pull request merged**
