### PR TITLE
Update Symfony Support

### PR DESCRIPTION
**Pull request by franmomu**
These are the changes:
- Remove Silex ~1.3 as is not supported since long time ago (I've just realised that there is a Silex 2.4 which has been deprecated for a year, but this one supports symfony ^4.0 packages, so I'm not sure if it should be introduced again)
~- Use phpunit 7.5 and for that I had to use also mockery > 1.0 and there was an error with nette/util that was fixed on 2.4~
- And for Symfony I bumped to the maintained versions

Closes https://github.com/cocur/slugify/issues/234

### CODE REVIEW

**Comment by florianeckerstorfer** [comment]
Awesome, can you fix the conflict and make the tests pass?

**Comment by franmomu** [comment]
I bumped phpunit to 6.5 and mockery to 1.2 so the php constraint with this is `^7.0`. Taking a look at https://github.com/cocur/slugify/pull/246, don’t know which versions are going to be dropped, I could make a PR just dropping 5.x or wait for that PR.

**Comment by florianeckerstorfer** [comment]
@franmomu If you have the time to create a PR to drop PHP 5 support, that would be awesome.

**Comment by franmomu** [comment]
I have no idea why scrutinizer fails

**Pull request merged**
