### PR TITLE
Create korean.json

### PR DESCRIPTION
**Pull request by MrMooky**
Building on a closed PR, I created a new one for Korean translation. I had one of my (Korean) customers quickly look over and got "There seems to be no problem with what you sent.".

### CODE REVIEW

**Review by florianeckerstorfer — APPROVED** [review]

**Comment by florianeckerstorfer** [comment]
Thank you so much for the PR. And sorry for the talking so long to merge it.

**Comment by dpDesignz** [comment]
Thanks for adding this! I've just started supporting Korean for one of my clients and this has come in super helpful. How can I add this to my project as I see it's not in the release code yet :(

**Comment by florianeckerstorfer** [comment]
@dpDesignz Released a new version 4.4

**Comment by dpDesignz** [comment]
> @dpDesignz Released a new version 4.4

Thanks, I've updated to 4.4.0, but I'm still getting a `ruleset 'korean' does not exist` error. Am I missing a step?

**Comment by florianeckerstorfer** [comment]
@dpDesignz It is not a default rule, you need to activate it

```
$slugify->activateRuleSet("korean");
```

**Comment by dpDesignz** [comment]
> @dpDesignz It is not a default rule, you need to activate it
> 
> ```
> $slugify->activateRuleSet("korean");
> ```

@florianeckerstorfer this is my code which I'm getting the error with

```php
// Get SEO friendly URL
$url = new Slugify();
$url->activateRuleSet('korean);
$url = $url->slugify($string);
```

It's the `$url->activateRuleSet('korean);` line that I'm getting the `ruleset 'korean' does not exist` error on

**Comment by dpDesignz** [comment]
Hey @florianeckerstorfer, just following this up please? :) It's still not working for me and I'm not sure where to look to test this.

**Comment by florianeckerstorfer** [comment]
@dpDesignz Sorry, my bad I didn't generate the default ruleset. Should be fixed in v4.5.0

**Pull request merged**
